version: '3'
networks:
  app-network:
    driver: bridge
services:
  load_balancer:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./private_key.key:/etc/nginx/private_key.key
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificate.crt:/etc/nginx/certificate.crt
    networks:
      - app-network
  image1:
    image: paulbouwer/hello-kubernetes:1.10
    networks:
      - app-network
  image2:
    image: paulbouwer/hello-kubernetes:1.10
    networks:
      - app-network